
# Generated by manual update for Rcpp interface

wARTP_cpp <- function(p_values, cor_mat, weights, B, fast = FALSE) {
    .Call('_metapro2_wARTP_cpp', p_values, cor_mat, weights, B)
}

ordmeta_cpp <- function(pvals, B = 20000) {
    .Call('_metapro2_ordmeta_cpp', pvals, B)
}
